window.PAGE_I18N = {
  zh: {
    pageTitle: "可用库存分析", heading: "可用库存分析", subtitle: "生成库存结果，并通过交互式图表查看可用库存趋势。", githubTitle: "GitHub 历史库存", githubTip: "生成结果会保存为 stock-history/Stock_YYYYMMDD.xlsx。同一天再次分析会覆盖当天文件。", githubRepo: "仓库（owner/repository）", githubBranch: "分支", githubToken: "GitHub Token", saveGithub: "保存配置", loadHistory: "加载历史库存", githubSaved: "GitHub 配置已保存。", githubMissing: "请填写仓库和 Token。", githubUploading: "正在保存到 GitHub……", githubUploaded: "已保存到 GitHub：{file}", historyLoading: "正在加载历史库存……", historyReady: "已加载 {count} 个历史文件。", historyFailed: "历史库存加载失败：{message}", historyDate: "日期", historyStock: "库存", historyTransit: "在途", historyAllocated: "待分配", historyNoData: "没有找到历史库存文件。",
    step1: "步骤 1：生成库存结果", engine: "处理引擎", engineJs: "JavaScript（推荐）", enginePy: "Python 旧版（备用）", engineTip: "JavaScript 直接在浏览器中运行；如遇 Excel 兼容问题，可使用 Python 旧版。",
    inventoryFile: "Inventory 文件（必选）", dailyFile: "Daily Supply Plan 文件（必选）", odpFile: "EUPV ODP MASTER（可选）", orderFile: "Orderfile Base Realtime（可选）", useDefault: "使用仓库默认文件", transitStart: "在途开始日期", transitEnd: "在途结束日期",
    generate: "生成库存文件", reset: "重置", backHome: "← 返回主页", runStatus: "运行状态", waiting: "等待运行……", downloadGenerated: "下载生成的文件",
    step2: "步骤 2：可用库存可视化", formulaTip: "可用库存公式：库存 + 累计在途到货。按 CRD 计算的待分配数量会按月标记在图表上。", multiTip: "多选提示：直接点击选项即可切换选中/取消，无需按 Ctrl。",
    inventoryOverview: "总库存概览", inventoryOverviewTip: "顶部为三种状态合计；PV 按 Power Bin 换算 MW，ESS、HP 展示 Quantity。DSP/ODP 状态统计范围为本次生成选择的日期。", inventoryBrand: "品牌", inventorySeries: "系列", clearOverviewFilters: "清除品牌/系列筛选", pvInventoryTotal: "PV 总库存", essInventoryTotal: "ESS 总库存", hpInventoryTotal: "HP 总库存", quantityUnit: "Quantity", pvStatusShare: "PV 库存状态", essStatusShare: "ESS 库存状态", hpStatusShare: "HP 库存状态", statusInventory: "在库（Inventory）", statusDailySupply: "在途（Daily Supply Plan）", statusOdp: "国内未发货（ODP）", statusCategory: "产品类型", statusName: "库存状态", statusValue: "数值", statusShare: "占比", noInventoryData: "当前筛选条件下没有该类库存",
    sourceInv: "Inventory / Daily Supply Plan", sourceOdp: "ODP 文件", sourceMixed: "混合（两个来源）", warehouse: "仓库（WH）", category: "类别", productReport: "Product TCL Report", family: "系列", product: "产品（型号 | SKU | 接头）", productTip: "提示：请先选择维度；产品选项会显示型号、SKU 和接头，便于查找。",
    startDate: "开始日期", endDate: "结束日期", granularity: "时间粒度", daily: "每日", weekly: "每周", monthly: "每月", lineMode: "曲线模式", lineTotal: "所选产品合计", lineProduct: "按产品拆分", lineWarehouse: "按仓库拆分", applyFilters: "应用筛选", clearFilters: "清除筛选", detailTitle: "库存与在途明细（仅显示到货日期列）", noData: "暂无数据。", noSelection: "未选择条件", selectedSummary: "已选 {count} 项：{preview}{suffix}",
    instructions: "使用说明", instruction1: "Inventory 文件来自 NewArk-Inventory 模块的 Inventory List 导出。", instruction2: "Daily Supply Plan 文件来自 NewArk-Planning 模块的 Supply Plan，选择起止月份后导出。", instruction3: "ODP 文件来自 SharePoint，请联系 Planning 或 PSR 团队获取。", instruction4: "Orderfile Base 文件来自 NewArk-Report Center PV 模块，选择月份后导出。", instruction5: "Inventory 和 Daily Supply Plan 为必选文件；ODP 和 Orderfile Base 为可选文件。",
    loadingPython: "正在加载 Python 运行环境（首次运行可能需要 20–60 秒）……", installing: "正在安装依赖：openpyxl……", loadingScript: "正在加载库存分析脚本……", environmentReady: "环境已就绪。请上传文件并点击“生成库存文件”。", preparingInputs: "正在准备输入文件……", runningPython: "正在运行可用库存分析……", preparingJs: "正在准备 JavaScript Excel 引擎……", runningJs: "正在运行 JavaScript 可用库存分析……",
    requiredFile: "请上传必选文件：{label}，或勾选仓库默认文件。", templateMissing: "未找到模板文件：{path}（HTTP {status}）", repoMissing: "未找到 {label} 的仓库默认文件：{path}（HTTP {status}）", invalidWorkbook: "{label} 不是有效的 .xlsx/.xlsm 工作簿（ZIP 格式），请重新导出后上传。", invalidDate: "可视化日期范围无效。", unknownModel: "未知型号", alloc: "待分配 {qty}", noFilterData: "当前筛选条件下没有数据", noFilterRows: "当前筛选条件未匹配到任何行。", noTransitHeaders: "所选日期范围内没有在途日期列。", noActiveData: "当前筛选条件下没有有效的库存、在途或待分配数据", zeroRows: "匹配行的库存、在途和待分配数量均为零。", excludedRows: "可视化提示：已排除 {count} 行零活动数据。", topLines: "可视化提示：已选择 {count} 个产品，按期末值显示前 {shown} 条曲线。", noSplitSeries: "拆分模式下没有可显示的数据系列。", noWarehouseSeries: "按仓库模式下没有可显示的数据系列。",
    availableStock: "可用库存", transitInv: "在途来源 - Inventory/DSP", transitOdp: "在途来源 - ODP", transitMixed: "在途来源 - 混合", toAllocate: "待分配 - {model}", unknownWarehouse: "未知", warehouseSeries: "仓库 {name}", axisAllocated: "待分配",
    noDetailRows: "没有明细数据。", noActiveRows: "没有有效的明细数据。", tableProduct: "产品（型号 | SKU | 接头）", inStock: "库存", inTransitRange: "在途（所选范围）", allocated: "待分配", availableQty: "可用数量", tableSummary: "行数：{rows} | 到货日期列：{dates} | 库存：{stock} | 在途：{transit} | 待分配：{allocated} | 可用数量：{available} | 颜色：蓝色=Inventory/Daily Supply，橙色=ODP，紫色=混合",
    download: "下载 {file}", generatedBuilding: "库存文件已生成，正在构建可视化数据……", generatedReady: "库存文件已生成，可视化已就绪。", failed: "失败：{message}", jsDone: "JavaScript 库存文件已生成。行数：{rows}，有效 SKU：{skus}。", jsFailed: "JavaScript 引擎失败：{message}", resetDone: "已重置。请上传文件后重新运行。", visualizationFailed: "可视化失败：{message}"
  },
  en: {
    pageTitle: "Available Stock Analysis", heading: "Available Stock Analysis", subtitle: "Generate stock output, then explore available stock trends with interactive visualization.", githubTitle: "GitHub Stock History", githubTip: "Results are saved as stock-history/Stock_YYYYMMDD.xlsx. Re-running on the same day overwrites that file.", githubRepo: "Repository (owner/repository)", githubBranch: "Branch", githubToken: "GitHub Token", saveGithub: "Save Configuration", loadHistory: "Load Stock History", githubSaved: "GitHub configuration saved.", githubMissing: "Enter repository and token.", githubUploading: "Saving to GitHub...", githubUploaded: "Saved to GitHub: {file}", historyLoading: "Loading stock history...", historyReady: "Loaded {count} historical files.", historyFailed: "Failed to load stock history: {message}", historyDate: "Date", historyStock: "Stock", historyTransit: "In transit", historyAllocated: "Allocated", historyNoData: "No historical stock files found.",
    step1: "Step 1: Generate Stock Output", engine: "Processing Engine", engineJs: "JavaScript (Recommended)", enginePy: "Python Legacy (Fallback)", engineTip: "JavaScript runs directly in the browser. Use Python Legacy if an Excel compatibility issue is encountered.",
    inventoryFile: "Inventory File (Required)", dailyFile: "Daily Supply Plan File (Required)", odpFile: "EUPV ODP MASTER (Optional)", orderFile: "Orderfile Base Realtime (Optional)", useDefault: "Use repository default file", transitStart: "Transit Start", transitEnd: "Transit End",
    generate: "Generate Stock File", reset: "Reset", backHome: "← Back to Home", runStatus: "Run Status", waiting: "Waiting to run...", downloadGenerated: "Download generated file",
    step2: "Step 2: Available Stock Visualization", formulaTip: "Available Stock formula: Stock + cumulative in-transit arrivals. CRD-based To be allocated is marked on the chart by month.", multiTip: "Multi-select tip: click items directly to toggle select/unselect (no Ctrl needed).",
    inventoryOverview: "Total Inventory Overview", inventoryOverviewTip: "Top totals combine all three statuses. PV is converted to MW using Power Bin; ESS and HP remain as Quantity. DSP/ODP use the generation date range.", inventoryBrand: "Brand", inventorySeries: "Series", clearOverviewFilters: "Clear brand/series filters", pvInventoryTotal: "PV Total Inventory", essInventoryTotal: "ESS Total Inventory", hpInventoryTotal: "HP Total Inventory", quantityUnit: "Quantity", pvStatusShare: "PV Inventory Status", essStatusShare: "ESS Inventory Status", hpStatusShare: "HP Inventory Status", statusInventory: "In stock (Inventory)", statusDailySupply: "In transit (Daily Supply Plan)", statusOdp: "Not shipped in China (ODP)", statusCategory: "Product Category", statusName: "Inventory Status", statusValue: "Value", statusShare: "Share", noInventoryData: "No inventory in this category under current filters",
    sourceInv: "Inventory / Daily Supply Plan", sourceOdp: "ODP File", sourceMixed: "Mixed (both sources)", warehouse: "Warehouse (WH)", category: "Category", productReport: "Product TCL Report", family: "Family", product: "Product (Model | SKU | Connector)", productTip: "Tip: select dimensions first. Product items show Model, SKU, and Connector for easier retrieval.",
    startDate: "Start Date", endDate: "End Date", granularity: "Granularity", daily: "Daily", weekly: "Weekly", monthly: "Monthly", lineMode: "Line Mode", lineTotal: "Total selected products", lineProduct: "Split by product", lineWarehouse: "Split by warehouse", applyFilters: "Apply Filters", clearFilters: "Clear Filters", detailTitle: "In-stock & In-transit Detail (arrival columns only)", noData: "No data.", noSelection: "No condition selected", selectedSummary: "{count} selected: {preview}{suffix}",
    instructions: "Instructions", instruction1: "Inventory file comes from the Inventory List export in the NewArk Inventory module.", instruction2: "Daily Supply Plan file comes from the Supply Plan export in the NewArk Planning module after selecting the start and end months.", instruction3: "The ODP file comes from SharePoint. Please contact the Planning or PSR team.", instruction4: "Orderfile Base comes from the NewArk Report Center PV module after selecting a month.", instruction5: "Inventory and Daily Supply Plan are required; ODP and Orderfile Base are optional.",
    loadingPython: "Loading Python runtime (first run may take 20–60 seconds)...", installing: "Installing dependency: openpyxl...", loadingScript: "Loading stock analysis script...", environmentReady: "Environment ready. Upload files and click Generate Stock File.", preparingInputs: "Preparing input files...", runningPython: "Running available stock analysis...", preparingJs: "Preparing JavaScript Excel engine...", runningJs: "Running JavaScript available stock analysis...",
    requiredFile: "Please upload required file: {label}, or select the repository default file.", templateMissing: "Template file not found: {path} (HTTP {status})", repoMissing: "{label} repository default file not found: {path} (HTTP {status})", invalidWorkbook: "{label} is not a valid .xlsx/.xlsm workbook (ZIP format). Please export it again and upload the new file.", invalidDate: "Invalid visualization date range.", unknownModel: "Unknown Model", alloc: "Alloc {qty}", noFilterData: "No data under current filters", noFilterRows: "No rows matched current filters.", noTransitHeaders: "No transit date headers in the selected date range.", noActiveData: "No active stock/transit/allocation under current filters", zeroRows: "All matched rows are zero-activity (Stock/Transit/To be allocated).", excludedRows: "Visualization note: excluded {count} zero-activity rows.", topLines: "Visualization note: {count} products selected, showing the top {shown} lines by ending value.", noSplitSeries: "No series available for split mode.", noWarehouseSeries: "No series available for warehouse mode.",
    availableStock: "Available Stock", transitInv: "Transit Source - Inventory/DSP", transitOdp: "Transit Source - ODP", transitMixed: "Transit Source - Mixed", toAllocate: "To be allocated - {model}", unknownWarehouse: "Unknown", warehouseSeries: "WH {name}", axisAllocated: "To be allocated",
    noDetailRows: "No detail rows.", noActiveRows: "No active detail rows.", tableProduct: "Product (Model | SKU | Connector)", inStock: "In-stock", inTransitRange: "In-transit (range)", allocated: "To be allocated", availableQty: "Available Qty", tableSummary: "Rows: {rows} | Arrival date columns: {dates} | In-stock: {stock} | In-transit: {transit} | To be allocated: {allocated} | Available Qty: {available} | Color tag: Blue=Inventory/Daily Supply, Orange=ODP, Purple=Mixed",
    download: "Download {file}", generatedBuilding: "Done: stock file generated. Building visualization data...", generatedReady: "Done: stock file generated and visualization is ready.", failed: "Failed: {message}", jsDone: "Done: JavaScript stock file generated. Rows: {rows}, active SKUs: {skus}.", jsFailed: "JavaScript engine failed: {message}", resetDone: "Reset complete. Upload files and run again.", visualizationFailed: "Visualization failed: {message}"
  }
};
