window.DEFAULT_PORT_MAPPINGS = [
  { type: "POL", raw: "NINGBO", standard: "NINGBO", country: "China", note: "" },
  { type: "POL", raw: "SHANGHAI", standard: "SHANGHAI", country: "China", note: "" },
  { type: "POL", raw: "SHENZHEN", standard: "SHENZHEN", country: "China", note: "" },
  { type: "POL", raw: "TIANJIN", standard: "TIANJIN", country: "China", note: "" },
  { type: "POL", raw: "ZHUHAI", standard: "ZHUHAI", country: "China", note: "" },

  { type: "DEST", raw: "AARHUS", standard: "AARHUS", country: "Denmark", note: "" },
  { type: "DEST", raw: "ANTWERP", standard: "ANTWERP", country: "Belgium", note: "" },
  { type: "DEST", raw: "AUGUSTA", standard: "AUGUSTA", country: "Italy", note: "" },
  { type: "DEST", raw: "CORK", standard: "CORK", country: "Ireland", note: "" },
  { type: "DEST", raw: "DAR ES SALAAM", standard: "DAR ES SALAAM", country: "Tanzania", note: "" },
  { type: "DEST", raw: "DOUALA", standard: "DOUALA", country: "Cameroon", note: "" },
  { type: "DEST", raw: "DURRES", standard: "DURRES", country: "Albania", note: "" },
  { type: "DEST", raw: "FELIXSTOWE", standard: "FELIXSTOWE", country: "United Kingdom", note: "" },
  { type: "DEST", raw: "FOS SUR MER", standard: "FOS SUR MER", country: "France", note: "" },
  { type: "DEST", raw: "GDANSK", standard: "GDANSK", country: "Poland", note: "" },
  { type: "DEST", raw: "GENOA", standard: "GENOA", country: "Italy", note: "" },
  { type: "DEST", raw: "GRANGEMOUTH", standard: "GRANGEMOUTH", country: "United Kingdom", note: "" },
  { type: "DEST", raw: "KARACHI", standard: "KARACHI", country: "Pakistan", note: "" },
  { type: "DEST", raw: "KLAIPEDA", standard: "KLAIPEDA", country: "Lithuania", note: "" },
  { type: "DEST", raw: "LAEM CHABANG", standard: "LAEM CHABANG", country: "Thailand", note: "" },
  { type: "DEST", raw: "LE HAVRE", standard: "LE HAVRE", country: "France", note: "" },
  { type: "DEST", raw: "LIMASSOL", standard: "LIMASSOL", country: "Cyprus", note: "" },
  { type: "DEST", raw: "MANILA NORTH", standard: "MANILA NORTH", country: "Philippines", note: "" },
  { type: "DEST", raw: "NAPLES", standard: "NAPLES", country: "Italy", note: "" },
  { type: "DEST", raw: "PIRAEUS-THESSALONIKI", standard: "THESSALONIKI", country: "Greece", note: "取后段 / Use final port" },
  { type: "DEST", raw: "POINTE DES GALETS", standard: "POINTE DES GALETS", country: "France (Réunion)", note: "" },
  { type: "DEST", raw: "RIJEKA", standard: "RIJEKA", country: "Croatia", note: "" },
  { type: "DEST", raw: "ROTTERDAM", standard: "ROTTERDAM", country: "Netherlands", note: "" },
  { type: "DEST", raw: "ROTTERDAM-CORK", standard: "CORK", country: "Ireland", note: "取后段 CORK / Use final port" },
  { type: "DEST", raw: "THESSALONIKI", standard: "THESSALONIKI", country: "Greece", note: "" },
  { type: "DEST", raw: "VALENCIA", standard: "VALENCIA", country: "Spain", note: "" },
];
